language: php
branches:
  only:
    - master
    - dev
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
script:
  - php phpcs.phar -v --standard=./phpcs.xml --encoding=utf-8 ./src/lib/Local/ ./src/shell/local/abstract.php